export const SET_INGREDIENT_DETAILS: "SET_INGREDIENT_DETAILS" =
  "SET_INGREDIENT_DETAILS";
export const DELETE_INGREDIENT_DETAILS: "DELETE_INGREDIENT_DETAILS" =
  "DELETE_INGREDIENT_DETAILS";

export const SET_BUN: "SET_BUN" = "SET_BUN";
export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const MOVE_INGREDIENT: "MOVE_INGREDIENT" = "MOVE_INGREDIENT";
export const CLEAR_CONSTRUCTOR: "CLEAR_CONSTRUCTOR" = "CLEAR_CONSTRUCTOR";

export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";

export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";

export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";

export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";

export const PASSWORD_FORGOT_SUCCESS: "PASSWORD_FORGOT_SUCCESS" =
  "PASSWORD_FORGOT_SUCCESS";

export const PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS" =
  "PASSWORD_RESET_SUCCESS";

export const REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS" =
  "REGISTRATION_SUCCESS";

export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";

export const PATCH_USER_SUCCESS: "PATCH_USER_SUCCESS" = "PATCH_USER_SUCCESS";

export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
export const WS_GET_ORDERS: "WS_GET_ORDERS" = "WS_GET_ORDERS";

export const WS_CONNECTION_START_USER: "WS_CONNECTION_START_USER" =
  "WS_CONNECTION_START_USER";
export const WS_CONNECTION_SUCCESS_USER: "WS_CONNECTION_SUCCESS_USER" =
  "WS_CONNECTION_SUCCESS_USER";
export const WS_CONNECTION_ERROR_USER: "WS_CONNECTION_ERROR_USER" =
  "WS_CONNECTION_ERROR_USER";
export const WS_CONNECTION_CLOSED_USER: "WS_CONNECTION_CLOSED_USER" =
  "WS_CONNECTION_CLOSED_USER";
export const WS_GET_ORDERS_USER: "WS_GET_ORDERS_USER" = "WS_GET_ORDERS_USER";
